name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    container: swift:6.0-noble
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          set -eu

          # Installation commands from https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository:

          # Add Docker's official GPG key:
          apt-get update -y
          apt-get install ca-certificates curl gnupg -y
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          chmod a+r /etc/apt/keyrings/docker.gpg

          # Add the repository to Apt sources:
          echo \
            "deb [arch=\"$(dpkg --print-architecture)\" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
              \"$(. /etc/os-release && echo "$VERSION_CODENAME")\" stable" |
            tee /etc/apt/sources.list.d/docker.list >/dev/null
          apt-get update -y

          # Install Docker:
          apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

      - name: Log in to the Container registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Install dependencies
        # zstd - Makes caching SPM builds DRAMATICALLY faster
        # libjemalloc-dev - Improves memory allocation performance in vapor
        run: |
          apt-get update -y
          apt-get install -y zstd
          apt-get install -y libjemalloc-dev

      - name: Restore .build
        id: "restore-build"
        uses: actions/cache/restore@v4
        with:
          path: .build
          key: "swiftpm-deploy-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
          restore-keys: "swiftpm-deploy-build-${{ runner.os }}-"

      - name: Build App
        run: |
          # Build the application, with optimizations, with static linking, and using jemalloc
          swift build \
            -c release \
            --product HaTrmnlVapor \
            --static-swift-stdlib \
            -Xlinker -ljemalloc \
            $([ -f ./Package.resolved ] && echo "--force-resolved-versions" || true)

      - name: Cache .build
        if: steps.restore-build.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .build
          key: "swiftpm-deploy-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: GIT_SHA=${{ github.sha }}
          file: Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Rancher
        uses: th0th/rancher-redeploy-workload@v0.82
        env:
          DEBUG: 'true'
          DISABLE_OUTPUT: 'false'
          RANCHER_BEARER_TOKEN: ${{ secrets.RANCHER_SECRET }}
          RANCHER_CLUSTER_ID: 'local'
          RANCHER_NAMESPACE: 'hadisplay'
          RANCHER_PROJECT_ID: 'p-tb6hn'
          RANCHER_URL: ${{ vars.RANCHER_URL }}
          RANCHER_WORKLOADS: 'hadisplay'
          TLS_SKIP_VERIFICATION: 'false'


