name: tests
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: swift:6.1-noble
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install zstd
        run: |
          apt-get update -y
          apt-get install -y zstd

      - name: Restore .build
        id: "restore-build"
        uses: actions/cache/restore@v4
        with:
          path: .build
          key: "swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"
          restore-keys: "swiftpm-tests-build-${{ runner.os }}-"

      - name: Build package
        run: swift build --build-tests --enable-code-coverage
        env:
            HA_URL: ${{ secrets.ENV_HA_URL }}
            HA_BEARER: ${{ secrets.ENV_HA_BEARER }}

      - name: Cache .build
        if: steps.restore-build.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: .build
          key: "swiftpm-tests-build-${{ runner.os }}-${{ github.event.pull_request.base.sha || github.event.after }}"


      - name: Run unit tests
        run: swift test --skip-build --enable-code-coverage --parallel --disable-xctest
        env:
            HA_URL: ${{ secrets.ENV_HA_URL }}
            HA_BEARER: ${{ secrets.ENV_HA_BEARER }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: info.lcov
